# Generated by Django 5.2.4 on 2025-07-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrcetapp', '0004_remove_patient_slug_patient_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
